### ISSUE TITLE
Project does not compile with component http client

### ISSUE THREAD

**Issue by OsvaldoTCF** [plasmapper/http-esp-cpp#1]
.platformio/packages/framework-espidf/components/esp_eth/include/esp_eth_mac_esp.h:205:35: error: invalid conversion from 'int' to 'emac_rmii_clock_gpio_t' [-fpermissive]

**Comment by plasmapper** [comment]
This is a [ESP-IDF bug](https://github.com/espressif/esp-idf/issues/14265) that is still present in v5.3.1 and should be fixed in the next release.
For now you can just make the [necessary changes](https://github.com/espressif/esp-idf/commit/e9df36a2dfe9ee074f421aedaff8952a348b339d#diff-d486024b46fb442e1174545fc43447df3cf6b4955c32bc3164f19e34fb3b1ef1) yourself in `components/esp_eth/include/esp_eth_mac_esp.h`.
